"""empty message

Revision ID: 39c16bd0d8a9
Revises: 712773399be1
Create Date: 2025-07-10 01:06:44.063525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c16bd0d8a9'
down_revision = '712773399be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
